import { db } from "../db/index.js";
import { series, video, renderJob, script } from "../db/schema.js";
import { CreateSimpleJobBody } from "../api/schemas/job-schemas.js";
import { eq, desc, and, sql, inArray, or } from "drizzle-orm";
import { hasEnoughCredits } from "./credit-service.js";
import { AppError } from "../lib/errors.js";
import {
    getOrCreateSeries,
    getNextEpisodeNumber,
    incrementSeriesEpisodeCount,
    createVideoRecord,
    createRenderJob,
    determineVideoTitle,
    CreateJobResult
} from "./shared-video-service.js";

// Re-export CreateJobBody type for backward compatibility
import { CreateJobBody } from "../api/jobs.js";
export type { CreateJobBody };

interface CreateVideoJobParams {
    userId: string;
    body: CreateSimpleJobBody;
    existingSeriesId?: string;
    isDraft?: boolean;
}

/**
 * Creates a video job using simple mode (script will be generated by worker)
 */
export async function createVideoJob({
    userId,
    body,
    existingSeriesId,
    isDraft = false
}: CreateVideoJobParams): Promise<CreateJobResult> {
    // 1. Check credits if not a draft
    if (!isDraft) {
        const canAfford = await hasEnoughCredits(userId, 1);
        if (!canAfford) {
            throw new AppError("InsuffCredits", "Insufficient credits to generate this video", 402);
        }
    }

    // 2. Build metadata (simple mode - no editor fields)
    const metadata = {
        duration: body.duration,
        segments: body.segments,
        visualFormat: body.visualFormat,
        visualStyle: body.visualStyle,
        voiceId: body.voiceId,
        subtitleTemplateId: body.subtitleTemplateId,
        musicId: body.musicId,
        scriptIdea: body.scriptIdea,
        nicheId: body.nicheId ?? undefined,
        aspectRatio: body.aspectRatio || "portrait",
        templateId: "simple",
    };

    // 3. Handle series creation/lookup
    const seriesName = body.jobType === "series" ? body.seriesName : undefined;
    const seriesId = await getOrCreateSeries(
        userId,
        body.jobType,
        seriesName,
        body.nicheId,
        body.scriptIdea,
        existingSeriesId
    );

    // 4. Determine episode number
    let episodeNumber = 1;
    if (existingSeriesId) {
        episodeNumber = await getNextEpisodeNumber(existingSeriesId);
        await incrementSeriesEpisodeCount(existingSeriesId);
    }

    // 5. Determine video title
    const isSeries = body.jobType === "series" || !!seriesId;
    const title = determineVideoTitle(
        body.episodeTitle,
        isSeries,
        seriesName,
        episodeNumber
    );

    // 6. Create video record
    // Simple mode always starts at SCRIPTING (worker generates script)
    const initialStatus = isDraft ? "DRAFT" : "SCRIPTING";

    const videoId = await createVideoRecord({
        userId,
        seriesId,
        nicheId: body.nicheId,
        title,
        episodeNumber,
        status: initialStatus,
        metadata
    });

    // 7. Create render job
    await createRenderJob(videoId, isDraft);

    return {
        success: true,
        message: "Job created successfully",
        seriesId,
        videoIds: [videoId]
    };
}

export async function deleteVideo(videoId: string, userId: string) {
    // Ensure the video belongs to the user
    const existingVideo = await db.select()
        .from(video)
        .where(and(eq(video.id, videoId), eq(video.userId, userId)))
        .limit(1);

    if (existingVideo.length === 0) {
        throw new Error("Video not found or access denied");
    }

    const v = existingVideo[0];

    // Check for active render jobs
    const activeJobs = await db.select()
        .from(renderJob)
        .where(
            and(
                eq(renderJob.videoId, videoId),
                or(eq(renderJob.status, "QUEUED"), eq(renderJob.status, "PROCESSING"))
            )
        )
        .limit(1);

    if (activeJobs.length > 0) {
        throw new Error("Cannot delete this video until the active generation job is finished.");
    }

    // If part of a series, decrement episode count
    if (v.seriesId) {
        await db.update(series)
            .set({
                episodeCount: sql`${series.episodeCount} - 1`,
                updatedAt: new Date()
            })
            .where(eq(series.id, v.seriesId));
    }

    // Delete related records first
    await db.delete(renderJob).where(eq(renderJob.videoId, videoId));
    await db.delete(script).where(eq(script.videoId, videoId));
    await db.delete(video).where(eq(video.id, videoId));

    return { success: true, message: "Video deleted successfully" };
}

export async function queueVideoRender(videoId: string, userId: string) {
    // Ensure the video belongs to the user and is in DRAFT
    const existingVideo = await db.select()
        .from(video)
        .where(and(eq(video.id, videoId), eq(video.userId, userId)))
        .limit(1);

    if (existingVideo.length === 0) {
        throw new Error("Video not found or access denied");
    }

    const v = existingVideo[0];
    const metadata = v.metadata as Record<string, any> | null;

    // Check credits
    const canAfford = await hasEnoughCredits(userId, 1);
    if (!canAfford) {
        throw new AppError("InsuffCredits", "Insufficient credits to generate this video", 402);
    }

    // Determine initial status based on whether this is an editor mode video
    // Editor mode videos have a pre-generated script and start at SCRIPT_READY
    const isEditorMode = metadata?.isEditorMode === true || v.mode === "editor";
    const initialStatus = isEditorMode ? "SCRIPT_READY" : "SCRIPTING";

    // Update video status
    await db.update(video)
        .set({ status: initialStatus, updatedAt: new Date() })
        .where(eq(video.id, videoId));

    // Update render_job status to QUEUED or VIDEO_QUEUED
    // Editor mode uses VIDEO_QUEUED to skip script generation
    const renderStatus = isEditorMode ? "VIDEO_QUEUED" : "QUEUED";

    await db.update(renderJob)
        .set({ status: renderStatus, updatedAt: new Date() })
        .where(eq(renderJob.videoId, videoId));

    return { success: true, message: "Rendering queued successfully" };
}

export async function updateVideoMetadata(videoId: string, userId: string, body: CreateSimpleJobBody) {
    // Ensure the video belongs to the user
    const existingVideo = await db.select()
        .from(video)
        .where(and(eq(video.id, videoId), eq(video.userId, userId)))
        .limit(1);

    if (existingVideo.length === 0) {
        throw new Error("Video not found or access denied");
    }

    const isDraft = body.isDraft || false;

    // Update metadata (simple mode - no editor fields)
    const metadata = {
        duration: body.duration,
        segments: body.segments,
        visualFormat: body.visualFormat,
        visualStyle: body.visualStyle,
        voiceId: body.voiceId,
        subtitleTemplateId: body.subtitleTemplateId,
        musicId: body.musicId,
        scriptIdea: body.scriptIdea,
        nicheId: body.nicheId ?? undefined,
        aspectRatio: body.aspectRatio || "portrait",
        templateId: "simple",
    };

    await db.update(video)
        .set({
            title: body.episodeTitle || existingVideo[0].title,
            status: isDraft ? "DRAFT" : "SCRIPTING",
            metadata,
            updatedAt: new Date()
        })
        .where(eq(video.id, videoId));

    // Update render_job status as well
    await db.update(renderJob)
        .set({
            status: isDraft ? "DRAFT" : "QUEUED",
            updatedAt: new Date()
        })
        .where(eq(renderJob.videoId, videoId));

    return { success: true, message: "Video updated successfully" };
}

export async function retryVideoProcessing(videoId: string, userId: string) {
    // Ensure the video belongs to the user
    const existingVideo = await db.select()
        .from(video)
        .where(and(eq(video.id, videoId), eq(video.userId, userId)))
        .limit(1);

    if (existingVideo.length === 0) {
        throw new Error("Video not found or access denied");
    }

    const v = existingVideo[0];
    const metadata = v.metadata as Record<string, any> | null;

    // Only allow retry for failed videos
    if (v.status !== "FAILED") {
        throw new Error("Only failed videos can be retried");
    }

    // Check credits
    const canAfford = await hasEnoughCredits(userId, 1);
    if (!canAfford) {
        throw new AppError("InsuffCredits", "Insufficient credits to retry this video", 402);
    }

    // Determine initial status based on whether this is an editor mode video
    const isEditorMode = metadata?.isEditorMode === true || v.mode === "editor";
    const initialStatus = isEditorMode ? "SCRIPT_READY" : "SCRIPTING";

    // Reset video status
    await db.update(video)
        .set({
            status: initialStatus,
            updatedAt: new Date()
        })
        .where(eq(video.id, videoId));

    // Reset render_job status to QUEUED or VIDEO_QUEUED
    // Editor mode uses VIDEO_QUEUED to skip script generation
    const renderStatus = isEditorMode ? "VIDEO_QUEUED" : "QUEUED";

    await db.update(renderJob)
        .set({
            status: renderStatus,
            error: null,
            retryCount: 0,
            progress: 0,
            updatedAt: new Date()
        })
        .where(eq(renderJob.videoId, videoId));

    return { success: true, message: "Video queued for reprocessing" };
}

export async function deleteSeries(seriesId: string, userId: string) {
    // 1. Ensure the series belongs to the user
    const existingSeries = await db.select()
        .from(series)
        .where(and(eq(series.id, seriesId), eq(series.userId, userId)))
        .limit(1);

    if (existingSeries.length === 0) {
        throw new Error("Series not found or access denied");
    }

    // 2. Find all video IDs in this series
    const seriesVideos = await db.select({ id: video.id })
        .from(video)
        .where(eq(video.seriesId, seriesId));

    const videoIds = seriesVideos.map(v => v.id);

    if (videoIds.length > 0) {
        // 3. Check for any active render jobs in this series
        const activeJobs = await db.select()
            .from(renderJob)
            .where(
                and(
                    inArray(renderJob.videoId, videoIds),
                    or(eq(renderJob.status, "QUEUED"), eq(renderJob.status, "PROCESSING"))
                )
            )
            .limit(1);

        if (activeJobs.length > 0) {
            throw new Error("Cannot delete this series while one or more videos have active generation jobs.");
        }

        // 4. Delete related records for all videos in the series
        await db.delete(renderJob).where(inArray(renderJob.videoId, videoIds));
        await db.delete(script).where(inArray(script.videoId, videoIds));
        await db.delete(video).where(inArray(video.id, videoIds));
    }

    // 5. Delete the series itself
    await db.delete(series).where(eq(series.id, seriesId));

    return { success: true, message: "Series and all associated videos deleted successfully" };
}
