server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;


    # Gzip compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Security Headers
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline' *.youtube.com *.google.com *.googleapis.com *.gstatic.com https://*.posthog.com; style-src 'self' 'unsafe-inline' *.googleapis.com; img-src 'self' blob: data: *.googleapis.com *.gstatic.com *.ytimg.com https://*.wasabisys.com; font-src 'self' data: *.gstatic.com; connect-src 'self' *.googleapis.com https://*.posthog.com https://*.getviralreel.com https://*.wasabisys.com; frame-src 'self' *.youtube.com; media-src 'self' https://*.wasabisys.com;" always;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Cache static assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}
