VIDEO_PROVIDER_SCRIPT = "VIDEO_PROVIDER_SCRIPT"
VIDEO_PROVIDER_TTS = "VIDEO_PROVIDER_TTS"
VIDEO_PROVIDER_IMAGE = "VIDEO_PROVIDER_IMAGE"
VIDEO_PROVIDER_STORAGE = "VIDEO_PROVIDER_STORAGE"
VIDEO_PROVIDER_COMPOSER = "VIDEO_PROVIDER_COMPOSER"

# Provider Values
PROVIDER_GOOGLE = "GOOGLE"
PROVIDER_MOCK = "MOCK"
PROVIDER_S3 = "S3"
PROVIDER_MOVIEPY = "MOVIEPY"
