ALTER TABLE "content_niche" ADD COLUMN IF NOT EXISTS "tags" text;
ALTER TABLE "content_niche" ADD COLUMN IF NOT EXISTS "icon_name" text;
ALTER TABLE "content_niche" ADD COLUMN IF NOT EXISTS "user_id" text DEFAULT 'admin';

INSERT INTO "content_niche" ("id", "name", "description", "tags", "icon_name", "user_id", "script_prompt", "video_prompt") VALUES
('true-crime', 'True Crime', 'Deep dives into mysterious cases, cold investigations, and detective stories.', 'mystery, documentary, investigation', 'Fingerprint', 'admin', 'Act as a seasoned investigative journalist. Write a gripping, suspenseful script about a real-life mystery. Focus on the timeline, the evidence, and the unsettling details that keep people awake at night. Use a somber, serious tone with dramatic pauses.', 'Cinematic, dramatic lighting, high contrast, documentary style, realistic textures, moody atmosphere.'),
('scary-stories', 'Scary Stories', 'Horror tales, creepypastas, and supernatural events narration.', 'horror, fiction, scary', 'Skull', 'admin', 'Act as a master of horror storytelling. Write a bone-chilling creepypasta or a supernatural encounter. Use descriptive, sensory language to build an atmosphere of dread. Include sudden shifts in tension and a lingering, haunting conclusion.', 'Dark, eerie, atmospheric horror, unsettling shadows, hyper-realistic, volumetric lighting, fog effects.'),
('history-facts', 'History & Facts', 'Educational content about historical events, ancient civilizations, and fun facts.', 'education, learning, history', 'History', 'admin', 'Act as a charismatic history professor. Narrate a significant historical event or an obscure but fascinating historical fact. Focus on the ''why'' and the human impact, making the past feel alive and relevant. Use an engaging, educational tone.', 'Epic historical recreations, rich color palettes, authentic period details, educational and majestic.'),
('science-tech', 'Science & Tech', 'Latest innovations, space discoveries, and futuristic concepts.', 'future, technology, science', 'Beaker', 'admin', 'Act as a visionary tech communicator. Explain a cutting-edge scientific discovery or a futuristic technology. Break down complex concepts into exciting, digestible insights that inspire wonder about the future. Use an optimistic and energetic tone.', 'Futuristic, high-tech, sleek, 3D renders, neon accents, clean aesthetics, space exploration themes.'),
('motivation', 'Motivation', 'Inspirational speeches, life advice, and personal growth content.', 'lifestyle, growth, motivation', 'Zap', 'admin', 'Act as a high-impact motivational speaker. Write a powerful speech centered on overcoming adversity, discipline, or personal growth. Use rhythmic phrasing, strong metaphors, and a crescendo of emotional intensity to inspire action.', 'Inspirational, bright lighting, dynamic movement, emotionally resonant, cinematic landscapes, uplifting.'),
('business-finance', 'Business & Finance', 'Market analysis, entrepreneurship tips, and money management.', 'money, startup, finance', 'TrendingUp', 'admin', 'Act as a savvy financial analyst. Discuss market trends, entrepreneurship, or wealth-building strategies. Provide clear, actionable insights with a focus on logic, strategy, and long-term success. Use a professional and authoritative tone.', 'Professional, clean, high-end corporate style, data visualizations, military quality, sophisticated lighting, authoritative.'),
('mindblowing-facts', 'Mindblowing Facts', 'Extraordinary facts that challenge common knowledge or reveal hidden wonders.', 'facts, wonder, mindblowing', 'Lightbulb', 'admin', 'Act as a curator of the extraordinary. Present a series of "did you know" facts that challenge common knowledge or reveal the hidden wonders of the world. Keep the pacing fast, the tone enthusiastic, and the focus on the "wow" factor.', 'Vibrant, fast-paced, high energy, colorful, surprising visuals, high-quality stock footage style.'),
('mysteries-unsolved', 'Mysteries & Unsolved', 'Explore unexplained phenomena, missing person cases, or bizarre anomalies.', 'mystery, unsolved, paranormal', 'Search', 'admin', 'Act as a narrator for a documentary on the unknown. Explore unexplained phenomena, missing person cases, or bizarre anomalies. Focus on the theories, the unanswered questions, and the sense of wonder or fear associated with the unknown.', 'Mysterious, low key lighting, grainy texture, suspenseful, conceptual art style, intriguing and dark.')
ON CONFLICT (id) DO UPDATE SET 
    icon_name = EXCLUDED.icon_name,
    description = EXCLUDED.description,
    tags = EXCLUDED.tags,
    user_id = EXCLUDED.user_id,
    script_prompt = EXCLUDED.script_prompt,
    video_prompt = EXCLUDED.video_prompt;